# Generated by Django 4.2.6 on 2023-10-12 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterClasses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterclass',
            name='price',
            field=models.PositiveIntegerField(),
        ),
    ]
